#!/usr/bin/env bash
# script that install Nginx

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://colorschemedesigner.com/csd-3.5/ permanent;" /etc/nginx/sites-available/default
service nginx start
