#!/usr/bin/env bash
# script that install Nginx

sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://colorschemedesigner.com/csd-3.5/ permanent;" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/error_404_not_found.html
sed -i "/server_name _;/ a\\\terror_page 404 \/error_404_not_found.html;\n\tlocation = \/error_404_not_found.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}" /etc/nginx/sites-enabled/default
service nginx start
