#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
PIDF=/var/run/holbertonscript.pid
echo $$ > $PIDF
i=1
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
trap 'echo I hate the kill command; rm -rf $PIDF; exit' TERM
trap 'echo "Y U no love me?!"' INT
while [ $i -ge 0 ]
	do
		echo "To infinity and beyond"
		sleep 2
	done