#!/usr/bin/env bash
# Script that loops from 1 to 10 and 4 bad luck and 8 good luck
x=1
while [ $x -le 100 ]
	do 
		if [ $(( x % 3 )) == 0 ]
			then
				echo "Fizz"
		elif [ $(( x % 5 )) == 0 ]
			then
				echo "Buzz"
		elif [ $(( x % 15 )) == 0 ]
			then
				echo "FizzBuzz"
		else
			echo "$x"
		fi
		x=$(( x + 1 ))
done
