#!/usr/bin/env bash
# Script that loops from 1 to 10 and 4 bad luck and 8 good luck
x=1
while [ $x -le 8 ]
	do 
		echo "Holberton School"
		if [ $x -eq 3 ]
			then
				echo "bad luck"
		elif [ $x -eq 6 ]
			then
				echo "good luck"
			fi
		x=$(( x + 1 ))
done
