#!/usr/bin/env bash
#script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i '/127.0.1.1/a 8.8.8.8 facebook.com' ~/hosts.new
sed -i 's/^127.0.0.1/127.0.0.2/' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
